apiVersion: v1
kind: Secret
metadata:
  name: postgres-ssh-key
  namespace: demo-gitops
type: Opaque
stringData:
  # Replace this value with your actual raw 'cat ~/.ssh/id_rsa.pub' string block
  authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAdLawGOChO3+pn1qb0r7k2dPXJ+bqw+6tdYvOiGuPJS jmaira@jmaira-mac"
