apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vm-disk
  namespace: demo-gitops
spec:
  storageClassName: portworx-kvirt-rwo
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi
